# Generated by Django 5.2.8 on 2025-11-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_product_real_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='real_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
            preserve_default=False,
        ),
    ]
