# Generated by Django 5.2.8 on 2025-11-08 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_real_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='real_price',
        ),
    ]
